services:
  database:
    image: ${DOCKER_REGISTRY-}carshop-db
    build:
      db/
    env_file: 
    - car-shop.env
    ports:
    - 5432:5432

  backend:
    image: ${DOCKER_REGISTRY-}carshop-back
    build:
      context: ./backend/CarShopBackEnd
      dockerfile: CarShopBackEnd/Dockerfile
    env_file: 
      - car-shop.env

    ports:
    - '5093:80'
    - '5094:443'
    depends_on:
      - database

  frontend:
    image: ${DOCKER_REGISTRY-}carshop-front

    build: 
      car-shop-app/

    ports:	
    - 4200:4200
    


