version: '3.4'

services:
  carshopbackend:
    image: ${DOCKER_REGISTRY-}carshopbackend
    build:
      context: ./backend/CarShopBackEnd
      dockerfile: CarShopBackEnd/Dockerfile
    ports:
    - '5093:80'
    - '5094:443'

  client:
    image: ${DOCKER_REGISTRY-}angular-docker
    build: 
      car-shop-app/

    ports:	
    - 4200:4200
      